import type { Course, CourseModule } from "./types";

type CourseSeed = Omit<Course, "duration" | "outcome" | "keywords"> & { keywords?: string[]; outcome?: string };
const make = (seed: CourseSeed): Course => ({ duration: "24 Weeks", outcome: "8 LPA", keywords: [], ...seed });
const mod = (title: string, description: string): CourseModule => ({ title, description });

export const courses: Course[] = [
  make({
    slug: "digital-marketing", cardTitle: "Digital Marketing", name: "Digital Marketing Course",
    title: "Digital Marketing Course | SEO & SMM Mentorship | EduWrap",
    description: "Become a full-stack Digital Marketer. Learn SEO, social media marketing, Google Ads, and analytics with real case studies and EduWrap's 1-on-1 mentorship.",
    keywords: ["digital marketing course", "SEO training online", "social media marketing", "Google Ads"],
    heroText: "Master SEO, SEM, content marketing, and more. Become a certified digital marketer.",
    overview: "Learn how digital marketing works across SEO, Google and Meta Ads, AI-powered advertising, OTT platforms, content marketing, and analytics. Discover how brands use these channels to reach the right audience and measure their results.",
    image: "/assets/images/Digital-Marketing-Course.webp",
    logos: ["Meta-Logo.webp", "google_ads_logo_icon_169088.webp", "Upwork-logo.webp", "Mailchimp Logo 50-50 Black.webp", "gtm.webp.original.webp", "Logo_Google_Analytics.svg.webp"],
    modules: [mod("Digital Marketing Fundamentals & SEO", "Learn keyword research, on-page and off-page SEO, Search Console, and organic growth."), mod("Social Media & Paid Advertising", "Master Meta and Google Ads, targeting, retargeting, A/B testing, and campaign budgeting."), mod("Content Marketing & Email Campaigns", "Create content strategies and high-converting email campaigns, then measure performance."), mod("Analytics, Portfolio & Career Placement", "Use GA4 and Tag Manager, complete a client project, and prepare for interviews.")],
    whyChooseUs: { title: "Why Choose Our Digital Marketing Course?", intro: "Train on the channels, campaign workflows, and reporting skills used by modern marketing teams.", reasons: [
      { icon: "search", title: "SEO That Drives Growth", text: "Plan keywords, optimize websites, and measure organic performance with practical SEO workflows." },
      { icon: "bullhorn", title: "Live Ad Campaign Skills", text: "Learn audience targeting, budgets, creatives, and optimization across Google and Meta Ads." },
      { icon: "line-chart", title: "Analytics-Led Decisions", text: "Use GA4 and Tag Manager to understand results and improve campaigns with reliable data." },
      { icon: "briefcase", title: "Campaign Portfolio", text: "Build case studies that demonstrate strategy, execution, reporting, and measurable outcomes." },
    ] },
  }),
  make({
    slug: "artificial-intelligence-machine-learning", cardTitle: "Artificial Intelligence & Machine Learning", name: "Artificial Intelligence and Machine Learning Course",
    title: "Artificial Intelligence & Machine Learning Course | EduWrap",
    description: "Master artificial intelligence, machine learning, prompt engineering, and practical AI implementations with EduWrap's expert-led mentorship program.",
    keywords: ["artificial intelligence course", "machine learning course", "AI and ML training", "prompt engineering"],
    heroText: "Build practical AI and machine learning skills for modern, real-world projects.",
    overview: "Explore the fundamentals of artificial intelligence and machine learning in our AI and ML course. Learn how AI tools and smart systems work, see how they’re used across industries, and build a foundation in the technologies shaping today’s world.",
    image: "/assets/images/Gen-Ai-Course.webp",
    logos: ["github.webp", "Scikit_learn.webp", "claude-ai-icon.webp", "ChatGPT-Logo.webp", "N8n-logo.webp", "tensor-flow.webp"],
    modules: [mod("Introduction to AI & Prompt Engineering", "Understand LLM fundamentals and learn to produce reliable results with modern AI tools."), mod("AI Tools & Workflow Automation", "Explore AI Studio and N8n, integrate APIs, and create automated workflows."), mod("Building Real-World AI Projects", "Build content generators, business automations, chatbots, and summarization tools."), mod("AI Career Preparation & Portfolio", "Create an AI portfolio and prepare for roles in AI products and automation.")],
    whyChooseUs: { title: "Why Choose Our AI & Machine Learning Course?", intro: "Move beyond AI theory by building useful systems with current models, tools, and automation platforms.", reasons: [
      { icon: "cogs", title: "Hands-On AI Workflows", text: "Create automations, assistants, and intelligent workflows that solve realistic business problems." },
      { icon: "code", title: "Practical Model Skills", text: "Understand model behavior, prompt design, APIs, evaluation, and responsible implementation." },
      { icon: "rocket", title: "Build Real AI Products", text: "Turn ideas into working chatbots, generators, summarizers, and productivity applications." },
      { icon: "github", title: "AI Project Portfolio", text: "Present complete, documented projects that show employers how you apply AI effectively." },
    ] },
  }),
  make({
    slug: "data-analytics", cardTitle: "Data Analytics", name: "Data Analytics Course",
    title: "Data Analytics Course Online | Master SQL & Python | EduWrap",
    description: "Extract insights and master Excel, SQL, Python, and BI tools to succeed in data careers with EduWrap's Data Analytics Mentorship Program.",
    keywords: ["data analytics course", "SQL training", "Python analytics", "Power BI"],
    heroText: "Extract insights, master Excel, SQL, Python, and BI tools to succeed in data careers.",
    overview: "Build practical data analytics skills and learn how data can support better decisions. In our Data Analytics course, you’ll work with Excel, SQL, Python, R Language, Power BI, and Tableau to turn raw data into clear reports and useful insights.-active data analysts.",
    image: "/assets/images/Data-analytics-course.webp",
    logos: ["MySQL.webp", "Microsoft_Office_Excel.webp", "python.webp", "matplotlib.webp", "NumPy_logo_2020.webp", "power-bi.webp"],
    modules: [mod("Excel & SQL for Data Analysis", "Master formulas, pivot tables, data cleansing, SQL queries, joins, and aggregations."), mod("Python for Data Science", "Use Pandas, NumPy, and Matplotlib for analysis and visualization."), mod("Power BI & Data Visualization", "Build dashboards and learn DAX, data modeling, and data storytelling."), mod("Capstone Project & Career Placement", "Complete an end-to-end analytics project and prepare for technical interviews.")],
    whyChooseUs: { title: "Why Choose Our Data Analytics Course?", intro: "Develop an end-to-end analytics toolkit for turning raw data into clear business recommendations.", reasons: [
      { icon: "database", title: "SQL for Real Data", text: "Query, join, clean, and summarize realistic datasets using professional SQL techniques." },
      { icon: "bar-chart", title: "Interactive BI Dashboards", text: "Build decision-ready Power BI reports with strong data models, DAX, and visual storytelling." },
      { icon: "file-excel-o", title: "Job-Ready Excel", text: "Master formulas, pivots, validation, and analysis workflows used across business teams." },
      { icon: "pie-chart", title: "End-to-End Capstone", text: "Solve a complete analytics problem and communicate findings through a polished portfolio project." },
    ] },
  }),
  make({
    slug: "web-development", cardTitle: "Web Development", name: "Web Development Course",
    title: "Full Stack Web Development Course | React, Node.js | EduWrap",
    description: "Learn full-stack Web Development with React, Node.js, and MongoDB. Build live projects and get 100% placement support.",
    keywords: ["full stack course", "React course", "Node.js training"],
    heroText: "Build full-stack dynamic websites, master React, Node.js, and modern CSS frameworks.",
    overview: "Learn how to turn website ideas into responsive web pages with our Web Development course. Explore HTML, CSS, JavaScript, REACT, Node.js, MongoDB and the basics of building user-friendly websites and web applications. It’s a practical choice among our IT and software development courses.",
    image: "/assets/images/web-development.webp",
    logos: ["bootstrap.webp", "react.webp", "Node.js_logo.webp", "express-js.webp", "MongoDB.webp", "nextjs.webp"],
    modules: [mod("Frontend Development (HTML, CSS, JS)", "Master HTML5, CSS3, responsive design, JavaScript, the DOM, events, and APIs."), mod("React.js Frontend Framework", "Learn components, hooks, state management, routing, and SPA architecture."), mod("Backend with Node.js & MongoDB", "Build REST APIs, model data, and implement secure authentication."), mod("Live Projects & Job Placement", "Deploy projects, build a portfolio, use Git, and prepare for interviews.")],
    whyChooseUs: { title: "Why Choose Our Web Development Course?", intro: "Learn the complete development cycle by designing, building, securing, and deploying modern web applications.", reasons: [
      { icon: "desktop", title: "Modern Frontend Skills", text: "Create responsive interfaces with HTML, CSS, JavaScript, React, and reusable components." },
      { icon: "server", title: "Complete Backend Training", text: "Build secure APIs, authentication, and data models with Node.js, Express, and MongoDB." },
      { icon: "cloud-upload", title: "Deploy Live Projects", text: "Take applications from local development to production and learn practical delivery workflows." },
      { icon: "code-fork", title: "Professional Git Portfolio", text: "Use version control properly and showcase full-stack projects through a credible portfolio." },
    ] },
  }),
  make({
    slug: "app-development", cardTitle: "App Development", name: "App Development Course",
    title: "Mobile App Development Course | Android & iOS | EduWrap",
    description: "Learn to build modern mobile apps for Android and iOS with practical projects, expert guidance, and job placement assistance.",
    keywords: ["mobile app development", "Flutter course", "React Native"],
    heroText: "Create iOS and Android mobile apps using React Native, Flutter, and modern mobile technologies.",
    overview: "Discover what goes into creating a mobile app from start to finish. The course covers app design, development basics, key features, and the tools used to build apps. You’ll gain a better understanding of how the apps you use every day are created.",
    image: "/assets/images/App-development.webp",
    logos: ["Android.webp", "apple_logo.webp", "Google-flutter.webp", "Node.js_logo.webp", "express-js.webp", "MongoDB.webp"],
    modules: [mod("Mobile App Fundamentals & UI Design", "Understand native and cross-platform development and design intuitive interfaces."), mod("Flutter / React Native Development", "Build apps with state management, navigation, animations, and reusable components."), mod("Backend Integration & Firebase", "Implement authentication, APIs, notifications, and real-time data."), mod("App Deployment & Job Placement", "Publish apps, build a portfolio, and prepare for interviews.")],
    whyChooseUs: { title: "Why Choose Our App Development Course?", intro: "Build polished cross-platform applications and learn every step from interface design to store deployment.", reasons: [
      { icon: "mobile", title: "Android & iOS Skills", text: "Create cross-platform experiences that work consistently across modern mobile devices." },
      { icon: "paint-brush", title: "Mobile-First UI Design", text: "Design intuitive screens, navigation, animations, and reusable interface components." },
      { icon: "bolt", title: "Firebase & API Integration", text: "Add authentication, real-time data, notifications, and external services to your apps." },
      { icon: "upload", title: "Store-Ready Projects", text: "Prepare applications for release and build a portfolio that demonstrates complete mobile delivery." },
    ] },
  }),
  make({
    slug: "autocad-sketchup", cardTitle: "AutoCAD and SketchUp", name: "AutoCAD and SketchUp Course",
    title: "AutoCAD & SketchUp Training Course | Learn 3D Modeling | EduWrap",
    description: "Master 3D modeling, rendering, architecture design, and drafting with AutoCAD and SketchUp.",
    keywords: ["AutoCAD course", "SketchUp training", "3D modeling"],
    heroText: "Learn 2D and 3D modeling for architecture, engineering, and product design.",
    overview: "Turn ideas into 2D drawings and 3D models using popular design tools. AutoCAD is useful for technical drafting, while SketchUp supports 3D design. These skills can be useful for learners interested in architecture and design.",
    image: "/assets/images/AutoCad_course_image.webp",
    logos: ["AutoCad_new_logo.webp", "SketchUp-logo.webp", "revit-logo.webp", "insmind-ai-logo.webp", "Shapr3d.webp", "tripo.webp"],
    modules: [mod("AutoCAD 2D Drafting Fundamentals", "Learn drawing tools, layers, annotation, dimensions, and technical drafting."), mod("AutoCAD 3D Modeling & Rendering", "Build solid models, apply materials, configure lighting, and render."), mod("SketchUp 3D Design & Visualization", "Model buildings and interiors using professional rendering workflows."), mod("Portfolio Projects & Career Placement", "Complete design projects and prepare for architecture and design roles.")],
    whyChooseUs: { title: "Why Choose Our AutoCAD & SketchUp Course?", intro: "Develop accurate drafting and expressive 3D visualization skills through practice-led design projects.", reasons: [
      { icon: "pencil-square-o", title: "Precision 2D Drafting", text: "Create professional plans, elevations, dimensions, annotations, and technical documentation." },
      { icon: "cube", title: "Detailed 3D Modeling", text: "Turn drawings into well-structured architectural, interior, and product models." },
      { icon: "sun-o", title: "Realistic Visualization", text: "Apply materials, lighting, scenes, and rendering techniques to communicate designs clearly." },
      { icon: "folder-open", title: "Design Portfolio Projects", text: "Complete presentation-ready work suited to architecture, engineering, and interior design roles." },
    ] },
  }),
  make({
    slug: "cyber-security", cardTitle: "Cyber Security", name: "Cyber Security Course",
    title: "Cyber Security Course & Certification | Ethical Hacking | EduWrap",
    description: "Learn ethical hacking, network security, and practical cyber defense strategies with EduWrap's Cyber Security Mentorship program.",
    keywords: ["cyber security course", "ethical hacking", "network security"],
    heroText: "Master ethical hacking, network defense, penetration testing, and secure modern systems.",
    overview: "Learn how to protect websites, networks, and data in our Cyber Security course. Explore ethical hacking, web security, and common online threats in clear, practical lessons. You’ll build a foundation for spotting risks and helping keep digital systems safe.",
    image: "/assets/images/Cyber-Security-course.webp",
    logos: ["kali_Linux.webp", "Tor_browser.webp", "Nagios.webp", "Metasploit_logo.webp", "Splunk_logo.webp", "Heimdal-Master_Logo.webp"],
    modules: [mod("Networking & Security Fundamentals", "Build foundations in TCP/IP, Linux, Windows, threats, and security principles."), mod("Ethical Hacking & Penetration Testing", "Practice reconnaissance, scanning, exploitation, and reporting."), mod("Web & Application Security", "Understand OWASP risks and test web applications and APIs securely."), mod("SOC, Certifications & Career Placement", "Practice incident response and prepare for security certifications.")],
    whyChooseUs: { title: "Why Choose Our Cyber Security Course?", intro: "Practice defensive and ethical offensive security in guided labs built around real attack scenarios.", reasons: [
      { icon: "shield", title: "Hands-On Security Labs", text: "Investigate threats and practice safely in controlled environments using industry tools." },
      { icon: "user-secret", title: "Ethical Hacking Practice", text: "Learn reconnaissance, vulnerability assessment, exploitation concepts, and clear reporting." },
      { icon: "globe", title: "Web Security Skills", text: "Understand OWASP risks and learn systematic testing approaches for applications and APIs." },
      { icon: "eye", title: "SOC & Incident Response", text: "Analyze events, identify suspicious behavior, and follow practical response procedures." },
    ] },
  }),
  make({
    slug: "tally-accounting", cardTitle: "Tally and Accounting", name: "Tally and Accounting Course",
    title: "Tally & Accounting Course Online | GST & ERP 9 | EduWrap",
    description: "Become a certified professional in Tally ERP 9, digital accounting, GST, and finance with 100% job placement assistance.",
    keywords: ["Tally course", "GST training", "accounting course"],
    heroText: "Become a certified professional in digital accounting, Tally ERP 9, GST, and finance.",
    overview: "Build your understanding of everyday accounting and business records. The course covers Tally Prime, GST, TDS, payroll, and basic financial reporting. It can help you become more comfortable with common accounting tasks.",
    image: "/assets/images/Tally-and-Accounting-Course.webp",
    logos: ["TallyPrime logo.webp", "ZohoBooks logo-crop.webp", "Gst.webp", "Microsoft_Office_Excel.webp", "nergy_vidya.webp", "ipr.webp"],
    modules: [mod("Accounting Fundamentals & TallyPrime", "Learn journal entries, ledgers, statements, inventory, and voucher entry."), mod("GST & Taxation", "Understand GST, tax credit, returns, e-invoicing, and compliance."), mod("Payroll & Digital Accounting Tools", "Learn payroll, PF, ESI, TDS, Zoho Books, and Excel."), mod("Financial Statements & Placement Support", "Prepare complete statements and receive dedicated career support.")],
    whyChooseUs: { title: "Why Choose Our Tally & Accounting Course?", intro: "Learn everyday accounting operations, taxation, payroll, and reporting through realistic business records.", reasons: [
      { icon: "calculator", title: "Practical TallyPrime Work", text: "Create companies, ledgers, vouchers, inventory records, and statements through guided exercises." },
      { icon: "file-text-o", title: "GST & Tax Compliance", text: "Understand input credit, returns, e-invoicing, TDS, and essential compliance workflows." },
      { icon: "money", title: "Payroll & Bookkeeping", text: "Manage payroll, PF, ESI, daily transactions, reconciliations, and financial records." },
      { icon: "balance-scale", title: "Business Case Studies", text: "Prepare complete accounts from source documents and interpret reports for decision-making." },
    ] },
  }),
  make({
    slug: "basic-computer-course", cardTitle: "Basic Computer Course", name: "Basic Computer Course",
    title: "Basic Computer Course | EduWrap",
    description: "Build essential computer skills in MS Office, typing, file management, and internet usage through practical training.",
    keywords: ["basic computer course", "computer fundamentals course", "MS Office training", "computer basics"], outcome: "Beginner",
    heroText: "Master essential computer skills, MS Office, typing, and the Internet to excel in the digital world.",
    overview: "Get comfortable using a computer for everyday tasks with our Basic Computer Course. Learn MS Word, Excel, PowerPoint, email, google forms and internet surfing through hands-on practice. Build the confidence to use these skills for studies, work, and daily life.",
    image: "/assets/images/advanced-computer-course.webp",
    logos: ["Microsoft_Office_Word.webp", "Microsoft_Office_Excel.webp", "Microsoft_Office_PowerPoint.webp", "gmail.webp", "Google_Drive.webp"],
    modules: [mod("Introduction to Computers", "Learn hardware, software, operating systems, and file management."), mod("MS Word Mastery", "Create and format professional documents, resumes, and letters."), mod("MS Excel Essentials", "Use spreadsheets, formulas, data entry, and visualizations."), mod("Internet & Presentations", "Browse safely, use email, and create engaging PowerPoint presentations.")],
    whyChooseUs: { title: "Why Choose Our Basic Computer Course?", intro: "Build confidence with the essential computer and office skills needed for study, work, and daily digital tasks.", reasons: [
      { icon: "windows", title: "Strong Computer Basics", text: "Understand files, folders, operating systems, hardware, software, and safe computer usage." },
      { icon: "file-word-o", title: "Complete MS Office Practice", text: "Create professional documents, spreadsheets, and presentations through practical assignments." },
      { icon: "keyboard-o", title: "Everyday Digital Skills", text: "Improve typing, email, web browsing, cloud storage, and online communication confidence." },
      { icon: "graduation-cap", title: "Beginner-Friendly Learning", text: "Progress step by step with clear demonstrations, guided practice, and doubt-solving support." },
    ] },
  }),
];

export const courseBySlug = (slug: string) => courses.find((course) => course.slug === slug);
