import Image from "next/image";
import Link from "next/link";
import { BlogCard } from "@/components/blog/BlogCard";
import { sanitizeBlogHtml } from "@/lib/blogs";
import { site } from "@/content/site";
import type { BlogPostRecord } from "@/types/blog";

export function BlogArticle({ blog, related = [], preview = false }: { blog: BlogPostRecord; related?: BlogPostRecord[]; preview?: boolean }) {
  const url = `${site.url}/blog/${blog.slug}`;
  return <main className="blog-article-page">{preview && <div className="blog-preview-banner"><i className="fa fa-eye" /> Secure admin preview — this content is not publicly listed.<Link href={`/admin/blogs/${blog.id}/edit`}>Return to editor</Link></div>}<div className="container"><nav className="blog-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><i className="fa fa-angle-right" /><Link href="/blog">Blog</Link><i className="fa fa-angle-right" /><span>{blog.title}</span></nav><article><header className="blog-article-header"><div className="blog-article-courses">{blog.courses.map((course) => <Link key={course.id} href={`/blog?course=${course.slug}`}>{course.name}</Link>)}</div><h1>{blog.title}</h1><p>{blog.excerpt}</p><div className="blog-article-byline"><span><i className="fa fa-user" /> By {blog.author.name}</span>{blog.publishedAt && <time dateTime={blog.publishedAt}><i className="fa fa-calendar" /> Published {new Date(blog.publishedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</time>}<time dateTime={blog.updatedAt}><i className="fa fa-refresh" /> Updated {new Date(blog.updatedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</time></div></header><div className="blog-article-image"><Image src={blog.featuredImage} alt={blog.featuredImageAlt} fill priority sizes="(max-width: 991px) 100vw, 900px" /></div><div className="blog-article-layout"><div className="blog-article-content" dangerouslySetInnerHTML={{ __html: sanitizeBlogHtml(blog.content) }} /><aside><div className="blog-share"><strong>Share this article</strong><div><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer" aria-label="Share on Facebook"><i className="fa fa-facebook" /></a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer" aria-label="Share on LinkedIn"><i className="fa fa-linkedin" /></a><a href={`https://wa.me/?text=${encodeURIComponent(`${blog.title} ${url}`)}`} target="_blank" rel="noopener noreferrer" aria-label="Share on WhatsApp"><i className="fa fa-whatsapp" /></a></div></div><div className="blog-course-links"><strong>Explore related courses</strong>{blog.courses.map((course) => <Link key={course.id} href={`/courses/${course.slug}`}>{course.name}<i className="fa fa-arrow-right" /></Link>)}</div></aside></div></article>{related.length > 0 && <section className="blog-related"><header><span>Continue learning</span><h2>Related articles</h2></header><div className="public-blog-grid">{related.map((post) => <BlogCard key={post.id} blog={post} />)}</div></section>}</div></main>;
}
